<?php

# #######################################################################
# Extension Manager/Repository config file for ext: "appointments"
#
# Auto generated by Extension Builder 2012-06-29
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
# #######################################################################
$EM_CONF[$_EXTKEY] = [
    'title' => 'Appointment Scheduler',
    'description' => 'Appointment scheduler allows FE users to schedule / list / manage appointments. Agenda\'s are created in BE, including user-defined appointment types, conditions, registration forms, and more.',
    'category' => 'plugin',
    'author' => 'Frenck Lutke',
    'author_email' => 'typo3@innologi.nl',
    'author_company' => 'www.innologi.nl',
    'state' => 'stable',
    'version' => '5.0.1',
    'constraints' => [
        'depends' => [
            'php' => '8.2.0-8.4.99',
            'typo3' => '13.4.0-13.4.99',
            'felogin' => '13.4.0',
            'tt_address' => '9.0.0-10.0.99',
        ],
        'conflicts' => [],
        'suggests' => [
            'scheduler' => '13.4.0',
        ],
    ],
    'autoload' => [
        'psr-4' => [
            'Innologi\\Appointments\\' => 'Classes',
        ],
    ],
];
