jQuery(document).ready(function(){function m(a){return parseInt(a.substring(0,a.indexOf(";",0)),10)}function p(){var a=(new Date).getTime()/1E3;if(Math.round(a-n)>=i)g=""}function q(a){var b=(new Date).getTime()/1E3;b=Math.round(b-n);a.remaining=a.seconds-b;if(!a.flashSet&&a.remaining<=a.flashStart){jQuery(a.element).addClass("flash");a.flashSet=true}else if(a.remaining<1){clearInterval(a.counter);if(r(a)){s();return}}b=Math.floor(a.remaining/60);var c="0"+a.remaining%60;jQuery(a.element).html(b+
":"+c.slice(-2))}function r(a){a=jQuery(a.element).parent(".tx-appointments .typo3-messages .alert.alert-info .alert-message");if(a[0]){var b=a.prev(".tx-appointments .typo3-messages .alert-title"),c=a.parent(".tx-appointments .typo3-messages .alert");if(b[0]&&c[0]){a.html("###TIMER_ZERO###");b.html("###TIMER_ZERO_HEAD###");c.addClass("alert-warning");c.removeClass("alert-info");return true}}return false}function s(){var a=jQuery(".tx-appointments form #appointments-submit-time");if(a[0]){a.val("###RENEW_TIME###");
a.addClass("attention")}}function t(){try{return"sessionStorage"in window&&window.sessionStorage!==null}catch(a){return false}}function j(a,b){sessionStorage.setItem(b+"_"+a.id,a.value)}function u(a){var b=jQuery(".session",a).map(function(){return this.id}).get();for(var c in b){var d=b[c],e=a.id+"_"+d;if(sessionStorage.getItem(e)){d=jQuery("#"+d,a);e=sessionStorage.getItem(e);if(d.hasClass("checkbox")||d.hasClass("radio"))e=="true"?d.prop("checked",true):d.prop("checked",false);else d.val(e)}}}
function v(a){var b=[];jQuery(a).attr("required")==="required"?b.push(a):jQuery(a).find('[required="required"]').each(function(c,d){b.push(d)});return b}function w(a,b,c){var d=jQuery(a.element);if(c&&b===a.enableValue){jQuery(a.required).attr("required","required");d.show()}else{d.hide();jQuery(a.required).removeAttr("required")}}function k(a,b){var c=jQuery(a).val().toLowerCase();a=jQuery(a).data("enable-fields");for(var d in a)w(a[d],c,b)}var n=(new Date).getTime()/1E3;jQuery(".tx-appointments .button_delete").click(function(a){if(confirm("###DELETE_CONFIRM###"))return true;
else{a.stopImmediatePropagation();return false}});var g="###WARN_UNLOAD###",i=null,h=null;if("###WARN_ON_LEAVE###"==="1")if(jQuery(".tx-appointments form.warnUnload")[0])if(g.length){g=g.replace("$1","###WARN_UNLOAD_S1###");h="###WARN_ON_LEAVE_RESPECT_REFRESH###";if(h=="meta-tag"){h=jQuery("meta[http-equiv=REFRESH]");if(h[0])i=m(h.attr("content"))}else if(h=="header")var x=jQuery.ajax({type:"HEAD"}).done(function(){var a=x.getResponseHeader("REFRESH");if(a!=null&&a.length)i=m(a)});window.addEventListener("beforeunload",
function(a){i!=null&&p();if(g.length)return a.returnValue=g});jQuery(".tx-appointments .allowUnload").on("submit",function(){g=""})}jQuery(".tx-appointments .csh").hover(function(){appear=true;if(jQuery(this).next().is(".tx-appointments span.tooltip")==false)if(tooltip=jQuery(this).attr("title")){jQuery(this).data("title",tooltip);jQuery(this).after(jQuery('<span class="tooltip" style="display:none;opacity:0;"/>').text(tooltip))}else appear=false;if(appear){jQuery(this).prop("title","");jQuery(this).next().css("display",
"inline-block").animate({opacity:0.85},150)}},function(){elem=jQuery(this).next();if(elem.is(".tx-appointments span.tooltip")){jQuery(elem).animate({opacity:0},150,function(){jQuery(this).css("display","none")});jQuery(this).prop("title",jQuery(this).data("title"))}});jQuery(".tx-appointments form .datepicker").datepicker({showOn:"focus",dateFormat:"dd-mm-yy",changeMonth:true,changeYear:true,constrainInput:true,firstDay:1,hideIfNoPrevNext:true,minDate:"-120y",yearRange:"-120y:+10",showOtherMonths:true,
selectOtherMonths:true,showWeek:true,dayNamesMin:["###DAY7###","###DAY1###","###DAY2###","###DAY3###","###DAY4###","###DAY5###","###DAY6###"],monthNamesShort:["###MON1###","###MON2###","###MON3###","###MON4###","###MON5###","###MON6###","###MON7###","###MON8###","###MON9###","###MON10###","###MON11###","###MON12###"]});jQuery(".tx-appointments form .datepicker.max-today").datepicker("option","maxDate","0");jQuery(".tx-appointments span.reservation-timer").each(function(){var a={seconds:0,remaining:0,
flashStart:60,flashSet:false,counter:null,element:this},b=jQuery(this).html(),c=b.indexOf(":",0),d=parseInt(b.substring(0,c),10);a.seconds=d*60+parseInt(b.substring(c+1),10);if(a.seconds<=a.flashStart){jQuery(this).addClass("flash");a.flashSet=true}a.counter=setInterval(q,1E3,a)});jQuery(".tx-appointments form #appointments-select-type").change(function(){jQuery(".tx-appointments form #appointments-submit-type").addClass("attention")});jQuery(".tx-appointments form #appointments-select-date").change(function(){jQuery(".tx-appointments form #appointments-submit-date").addClass("attention")});
jQuery(".tx-appointments form #appointments-select-time").change(function(){jQuery(".tx-appointments form #appointments-submit-time").addClass("attention")});jQuery(".tx-appointments .appointment-form.disabled :input").prop("disabled",true);jQuery(".tx-appointments .appointment-form.disabled").addClass("visible");t()&&jQuery(".tx-appointments form.session").each(function(){var a=this.id;u(this);jQuery("textarea.session",this).keyup(function(){j(this,a)});jQuery(".textinput.session",this).keyup(function(){j(this,
a)});jQuery(".datepicker.session",this).change(function(){j(this,a)});jQuery(".select.session",this).change(function(){j(this,a)});jQuery(".radio.session",this).change(function(){sessionStorage.setItem(a+"_"+this.id,this.checked);jQuery(this).siblings('.radio.session[name="'+jQuery(this).attr("name")+'"]').each(function(b,c){sessionStorage.setItem(a+"_"+c.id,c.checked)})});jQuery(".checkbox.session",this).change(function(){sessionStorage.setItem(a+"_"+this.id,this.checked)})});var f={};jQuery(".tx-appointments form .enablefield").each(function(a,
b){var c=jQuery(b).attr("class"),d=c.indexOf("eval-f")+6;d=c.slice(d).split("-");c=d[0];d=d[1].split(" ")[0].toLowerCase();var e=null;if(f[c]!==undefined)e=f[c];else{e=jQuery(".tx-appointments form .formfield-id-"+c);if(e[0]){f[c]=e;e.data("enable-fields",{});e.hasClass("radio")?e.change(function(){k(this,this.checked)}):e.change(function(){k(this,true)})}}if(e[0]){c=jQuery(e[0]).data("enable-fields");c[a]={element:b,enableValue:d,required:v(b)};e.data("enable-fields",c)}});for(var l in f)if(f[l].hasClass("radio")){var o=
false;f[l].each(function(a,b){if(this.checked){k(b,true);o=true;return false}});o||k(f[l][0],false)}else f[l].change()});